# Generated by Django 3.2.6 on 2021-08-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_img',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='default product', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
